### ISSUE TITLE
Error starting the GTK UI

### ISSUE THREAD

**Issue by petersasi** [mhertz/deluge2#1] opened 2021-02-16 15:21 UTC
Hi MHertz, Peter Sasi here working on a major rewamp. I am a bit stuck. Don't worry I have not found any issue with your code just do not know how can I message you on github, and I was hoping you might have faced the below error and might know the root cause. :)
So deluged, deluge-console and deluge-web start just fine
- however deluge.exe, deluge-GTK and deluge-debug all fail to start with this error:
```
C:\Program Files\Deluge>deluge-debug.exe
23:14:12.540 [ERROR   ][deluge.ui.gtk3                    :52  ] [WinError 87] The parameter is incorrect: './data/bin'
Traceback (most recent call last):
  File "C:\Program Files\Deluge\lib\site-packages\deluge\ui\gtk3\__init__.py", line 49, in run
    gtkui = GtkUI(options)
  File "C:\Program Files\Deluge\lib\site-packages\deluge\ui\gtk3\gtkui.py", line 201, in __init__
    self.torrentdetails = TorrentDetails()
  File "C:\Program Files\Deluge\lib\site-packages\deluge\ui\gtk3\torrentdetails.py", line 119, in __init__
    from .status_tab import StatusTab
  File "C:\Program Files\Deluge\lib\site-packages\deluge\ui\gtk3\status_tab.py", line 18, in <module>
    from .piecesbar import PiecesBar
  File "C:\Program Files\Deluge\lib\site-packages\deluge\ui\gtk3\piecesbar.py", line 20, in <module>
    import cairo  # Backward compat cairo <= 1.15
  File "C:\Program Files\Deluge\lib\site-packages\cairo\__init__.py", line 8, in <module>
    added_dirs.append(os.add_dll_directory(p))
  File "C:\Program Files\Deluge\lib\os.py", line 1111, in add_dll_directory
    cookie = nt._add_dll_directory(path)
OSError: [WinError 87] The parameter is incorrect: './data/bin'
Traceback (most recent call last):
  File "C:\Program Files\Deluge\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Deluge\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Deluge\deluge-debug.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Deluge\lib\site-packages\deluge\ui\ui_entry.py", line 143, in start_ui
    ui.start()
  File "C:\Program Files\Deluge\lib\site-packages\deluge\ui\gtk3\__init__.py", line 55, in start
    deluge.common.run_profiled(
  File "C:\Program Files\Deluge\lib\site-packages\deluge\common.py", line 1351, in run_profiled
    return func(*args)
  File "C:\Program Files\Deluge\lib\site-packages\deluge\ui\gtk3\__init__.py", line 49, in run
    gtkui = GtkUI(options)
  File "C:\Program Files\Deluge\lib\site-packages\deluge\ui\gtk3\gtkui.py", line 201, in __init__
    self.torrentdetails = TorrentDetails()
  File "C:\Program Files\Deluge\lib\site-packages\deluge\ui\gtk3\torrentdetails.py", line 119, in __init__
    from .status_tab import StatusTab
  File "C:\Program Files\Deluge\lib\site-packages\deluge\ui\gtk3\status_tab.py", line 18, in <module>
    from .piecesbar import PiecesBar
  File "C:\Program Files\Deluge\lib\site-packages\deluge\ui\gtk3\piecesbar.py", line 20, in <module>
    import cairo  # Backward compat cairo <= 1.15
  File "C:\Program Files\Deluge\lib\site-packages\cairo\__init__.py", line 8, in <module>
    added_dirs.append(os.add_dll_directory(p))
  File "C:\Program Files\Deluge\lib\os.py", line 1111, in add_dll_directory
    cookie = nt._add_dll_directory(path)
OSError: [WinError 87] The parameter is incorrect: './data/bin'
```
Have you ever seen similar? Can it be slash vs. backslash? Or maybe python.exe vs. pythonw.exe?

I have already turned off all file removal to make sure it is not a missing file. This way the built installer is 65MB 🙈 (you can see it on the usual google drive, all the latest versions) But I shave it off once I figure this out...

And my Program Files\Deluge\data\bin\ has all the dlls:
```
C:\Program Files\Deluge\data\bin>dir /w
 Volume in drive C is Windows
 Directory of C:\Program Files\Deluge\data\bin
[.]                      [..]                     asprintf.dll             atk-1.0-0.dll
cairo-gobject.dll        cairo.dll                cogl-1.0.dll             cogl-pango-1.0.dll
cogl-path-1.0.dll        epoxy-0.dll              ffi-7.dll                fontconfig.dll
freetype-6.dll           fribidi-0.dll            gailutil-3-vs16.dll      gdk-3-vs16.dll
gdk_pixbuf-2.0-0.dll     gettextlib.dll           gettextpo.dll            gettextsrc.dll
gio-2.0-0.dll            girepository-1.0-1.dll   glib-2.0-0.dll           gmodule-2.0-0.dll
gobject-2.0-0.dll        gthread-2.0-0.dll        gtk-3-vs16.dll           harfbuzz-gobject.dll
harfbuzz-subset.dll      harfbuzz.dll             iconv.dll                intl.dll
jasper.dll               jpeg62.dll               json-glib-1.0-0.dll      libenchant.dll
liblz4.dll               libpng16.dll             libxml2.dll              msvcp140.dll
pango-1.0-0.dll          pangocairo-1.0-0.dll     pangoft2-1.0-0.dll       pangowin32-1.0-0.dll
pkgconf-3.dll            rsvg-2.0-vs16.dll        tiff.dll                 tiffxx.dll
turbojpeg.dll            wing-1.0-0.dll           zlib1.dll
              49 File(s)     34,103,176 bytes
               2 Dir(s)  408,191,516,672 bytes free
C:\Program Files\Deluge\data\bin>
```

Thanks,
Peter

**Comment by mhertz** [comment] 2021-02-16 15:59
Hi Peter :)

Hmm, I will look into it in a few hours when having time and return to you with reply.

os.add_dll_directory doesn't take relative paths, and so needs preceding abspath-call to make absolute, but you are already during it I presume. Or else it's stating it cannot find the relative dir, which just is lib in your build and a zip in mine so why I add an extra parent-dir call. Why only works with daemons is strange, but only needs one file from that dir when notusing gtk3 and if already having that on system, then maybe was a silent error before, but not sure honestly.

Anyway, I download your build now and see if I can see something with it later in some hours.

I'll add a 'discusion' feature, though don't mind whereever you post.

**Comment by mhertz** [comment] 2021-02-16 16:25
I haven't checked yet, but just downloaded and extracted installers to look at later, and noticed the icons where off in the failing exe's, plus there filesizes show the alternative loader not used, so something must have gone wrong during building presumably, just strange only some of them include the loader - they get "repatched" later with the loader again, but is same loader as the rest used during building, so either was copied correct over or not, and I don't understand how they are mixed. though that alone I guess shouldn't matter, if remember correct, but just sounds like something did infact go wrong, so if rerunning at some point, then examine output for issues or send me the script youre currently using.

**Comment by petersasi** [comment] 2021-02-16 16:29
Thanks, for one I didn't really modify much in the build just upgraded
versions and rebuild... Definitely not editing or patching sources for
relative or absolute paths.

My hunch is maybe that my GTK build silently screws up and only the exes
that do not need it work... But normally gvsbuild would just fail, not
build a not working version...

I would be very grateful if you could take a look, maybe compare to your
working version!

Thanks again,
Peter

**Comment by mhertz** [comment] 2021-02-16 22:01
Happy to help you mate! :)

Sorry took longer than I thought to troubleshoot/test.

Your gtk3 build works fine. Its a strange error, about the patched cairo init.py tries to use relative path in os.add_dll_directory which isn't supported, and no idea why tries that, as should pick up dir correctly from data\bin when finding caro.dll, but anyway, when exchanging cairo out with my build(under 'Lib\site-packages\cairo'), which just is regular build from gvsbuild, then works, except complaints about your libtorrent build for some reason, so exchanging that with mine makes the GTKUI start fine again. This is all for the 'allfiles' build however, as the cleaned version needs some extra deleted stuff from said 'allfiles' version: 'Lib\site-packages\certifi-2020.12.5.dist-info\METADATA', specifically, plus there's missing icons from icon-theme, and sorry, to lazy to find the 5 or more missing icons, at least right now, so if you could just include the whole folder, atleast for now, of: 'data\share\icons\Adwaita\scalable'. Then the window opens atleast and looks normal, with libtorrent connected and no errors in the terminal anymore from running the debug.exe and I didn't look further then that.

Not as important, but as said the alternative loader isn't used for most exe's, as seen by filesize and icons. I can see the loaders is copied over fine, but the exe's built a minute or so before the loader was copied over, hence original loaders used and just got the correct one for the daemons because they get patched again and rewritten with the aternative loader later, so after it was copied over.

Let me know if need help otherwise.

Btw, I apologize I wrote in the #3201 ticket that you was busy when you just had released a new build doh! :) Lastly, I started making builds on the forum in your thread, not because I thought it couldn't wait for longer time before new build, which obviously could and not my buisness, but because a user asked for help and I guessed possibly a GTK3 update would help, or something along those lines if remember correct and then kinda snowballed from there, but anyway, happy to see you back is what i'm getting at :)

-Martin.

**Comment by petersasi** [comment] 2021-02-17 02:58
Maybe my understanding of python is lacking, but I see this in `__init__.py` - to me this says it iterates through the dirs in the PATH environment variable of the OS 
```
    path = os.environ.get('PATH', '')
    for p in path.split(os.pathsep):
        if os.path.isfile(os.path.join(p, 'cairo.dll')):
            # Found a cairo.dll -> add to the list
            added_dirs.append(os.add_dll_directory(p))
```
But mine does not even have data\bin:
```
C:\Program Files\Deluge>echo %PATH%
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\PéterSasi\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Microsoft Office\root\Client
```
Is that added by some internal python logic maybe?

**Comment by petersasi** [comment] 2021-02-17 03:14
I have added:
```
    path = os.environ.get('PATH', '')
    print('Current path to be processed in cairo init looking for DLLs is:',path)
```
And the result is: (line breaks again by me)
```
C:\Program Files\Deluge>deluge-debug.exe -L warning
Current path to be processed in cairo init looking for DLLs is:
 ./data/bin;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Windows\System32\OpenSSH\;
C:\Users\PéterSasi\AppData\Local\Microsoft\WindowsApps;;
C:\Program Files\Microsoft Office\root\Client
```
Is it possible it is coming from `c:\Program Files\Deluge\Lib\site-packages\path.pth` which is this on my build (I think I copied the updated version from you:
`import os; os.chdir(os.path.join(os.path.dirname( __file__),os.path.pardir)); os.add_dll_directory(os.path.abspath("./data/bin")); os.environ["PATH"] = "./data/bin" + os.pathsep + os.environ['PATH']`

**Comment by mhertz** [comment] 2021-02-17 10:00
The pth file is a trick I use to add to path needed dir for gtk3(and os.add_dll_directories() in py3.8+), before a python app is started and only used for the session so not lingers after ending deluge. Plus I use it for the gtk_csd=0 and portable installer options, as might as well do it there when having such anyway.

I forgot something, and that is that I have two patches that I apply, well reverse, which removes the code in init that parses path for cairo and adds to os.add_dll_directory. I do this because I already do it, with correct dir, and because I was affraid it could break something i.e. it checks whole path for cairo.dll and adds those dirs found to os.add_dll_directory, but right order of that cannot be guarentied in that call, and I need ours to be the first, as there where many problems initially with dll's like cairo in e.g. system32 or otherwhere breaking deluge from starting.

Sorry, after your test, then I can see that indeed I set that from the pth, which I forgot I did doh, but though isn't an issue because I patched that init cairo code out here, and the relative path was supported for PATH only, just not the os.add_dll_directory, which is why I call it through the abspath call firstly.

I'm thinking you have deleted the two pathes for cairo and pygobject whl's because have 3.8 in name, but they still work fine, and I was too lazy to rename them, but did test eveything still worked and they was working in my 3.9.x upgrade.

**Comment by petersasi** [comment] 2021-02-21 11:08
I just ended up changing the path.pth file on overlay (an in the portable dirs as well) to use absolute paths with
`os.environ["PATH"]=os.path.abspath("./data/bin")+os.pathsep+os.environ['PATH']` so that the PATH is correct and we need no patching for this - the less patches needed the easier the maintenance gets. :)

**Comment by petersasi** [comment] 2021-02-21 11:45
BTW, thanks for catching the loader not used problem, I have moved Python initialization used by so many scripts including pip to a separate file, then also made a single pip install all modules and build deluge as well. Just forgot that then I need to move the loader copy to before this pip. 🤦 😄

**Comment by petersasi** [comment] 2021-02-21 14:06
Thanks for all the help, now I have a working GTK, working libtorrent (with Whole Program Optimization!) working python deluge.
At the same time, may I ask for your further help?
What is the method how you quickly find out the files missing?
Now I have disabled removing all of the scalable icons, still starting deluge-gtk (or deluge or deluge-debug) displays no icons, and even if starting with -L debug it does not give me any missing file messages 😞 
Any advice how to debud what is missing or is in the wrong place?

**Comment by mhertz** [comment] 2021-02-21 18:29
Cool you figured it out mate! :)

About your changes to the pth's, you can change to real instead of relative path if preffered, i'm just the lazy type so don't wanted to, when not strictly needed, but I still would suggest to patch out that part from pycairo and pygobject, as since stated it's a possible failure point, as many programs when installed dumps cairo.dll different places e.g. system32 and without the extra patching I used you can easily end up with such dll loaded before your wanted dll and break deluge, but your choise of-course(it's also faster, as no search for cairo.dll every time starting deluge from whole PATH). 

If haven't already, i'd suggest adding that *._pth file to further isolate deluge, just a text file with a few entries, which is another failure-point if e.g. people have a PYTHONPATH env-var defined etc.

About quickly finding missing files, then I don't know how quick I am lol, and just do manual looking/testing, so affraid I don't have any actual tips to help sorry, but i'll take a look also and see if can find something.

I don't know if being today though - there was a user asking for help with my win7 repo, so I have debugged that and found a few issues which took most of the day today lol .

I closed the issue before, because thought you was finished with your problem sorry :)

Great job enabling LTO and whatnot :)

**Comment by mhertz** [comment] 2021-02-21 20:49
Btw, went and downloaded your installer so ready for looking up the missing files at some later point, and then saw you had uploaded a new one, with the new fixes from today from Cas :) I also built that earlier today, (and whole gtk3 stack, damn that takes long :) ), during my win7-x86 troubleshooting, great too see Cas at it again now! :)

Anyway, just wanted to say that the current version you posted, (and the snippet posted earlier), need an extra dot in the path you make absolute through the abspath call, atleast in the way you do it in rest of that file. I only use one dot in mine(besides not using extra abspath call to make the relative path absolute for the PATH env-var addition, as relative path's is supported fine from PATH env-var, just not in os.add_dll_directory calls), but it doesn't matter whatsoever, just that it's consistent i.e. have to match what's initially done for the os.chdir command i.e. if not adding a pardir() call like I do, then two dots, and else 1.

Anyway, untill we find exactly what files needed for the icons, then you could just exclude whole data/share/icons/adwaita folder from your cleanup, to get the release out quicker, but your call.

**Comment by mhertz** [comment] 2021-02-21 20:58
Sorry for all the posts in row lol, but often an edit can be missed, as i've did myself several times and found maybe months after by mistake ;)

Anyway, I just wanted to state that libtorrent.pyd isn't loaded for me either, like in the previous dev46 allfiles and cleaned versions of yours, and I needed replace with mine. I don't know if that LTO makes it not be importable here or whatever the issue is, but it states only thinclient mode is available as no libtorrent could be found or not imported correct.

**Comment by mhertz** [comment] 2021-02-21 23:52
Sorry, I have narrowed it down to the scalable folder only, as originally stated, and just did again, so don't know why doesn't work for you? I copied a full working Adwaita icon theme folder over, from the allfiles previous dev46 version, and then I renamed one folder inside at a time with a _ infront of folder-name and started deluge again and saw if icons worked or not, and I did that with all the folders, to see whcih could be excluded, and only folder-rename breaking deluge-icons where scalable folder. Then inside that I did the same, and each deluge-startup could see that there where various icons, small or big, spread over several various folders, and honestly i'm not gonna bother disect that, but if you want that fine detail work on your end, then that's the way I did it. 

In my installer/repo, then I as said just delete the cursors folder and keep rest from the adwaita icon theme, as not care about a few extra megs, but anyway now after having gone through this little further disecting, then I atleast found that I can now delete everything except the scalable folder, and save some extra space, so instead of 9'ish MB it's then 1.66 MB roughly, so i'm glad to find that out, but as said the last few KB I don't find the work worth doing for me atleast.

Btw, the icons used are referenced in the deluge source in a file called something with main_window.ui or something, and under something like UI/gtk3/glade/main_window.ui, or something, cannot remember from top of head, and to lazy to lookup now sorry. There's not paths listed unfortunetly, just names, and not extension, so not knowing if svg or png, but each of those names are "code-names" so windows knows where to find them, maybe from that generated index.theme file or something I don't know, but can help also to narrow it down, e.g. enter the names one at a time into a searchbox fro the adwaita folder and see where located, if wanted.

Sorry cannot help you with why not working on your end when not cleaning scalables folder? It's not needed on my end here, as said, but does remember one time where I needed reset the icon cache because windows showed me a cached version of icons - I googled it and found a command that could be run from cmd-prompt which quickly reset the icon-cache - or explorer.exe could be restarted, or the cache file(s) could be deleted manually, but don't remember the command sorry, but google is your friend, though doubt it's that since I see the icons change at every deluge startup from renaming folders, but just didn't have any other thoughts/ideas from top of head, so just threw out there just in case.

Good luck mate :)

**Comment by mhertz** [comment] 2021-02-22 20:37
Sorry, just wanted to add, that I added some slight info to some of previous posts, but not important.

I saw your new installer and tested, and I just came to think about that I always test by rightclicking installers and selecting extract to a folder with same name with 7-zip and then at end select 'yes to all' to the error message about conflicting files, because there's several libtorent.pyd's and path.pth's etc.

Anyway, it's when doing that which made libtorrent not work, so atleast one of the libtorrents don't work from installer, but when running installer and selecting portable install then libtorrent works i.e. the default 1.2.13.

Last, you're missing some icon files from that scalable folder of adwaita icon theme, so something is wrong there. I tested with just taking my adwaita icon theme from my installer and adding to yours and there only scalable folder was needed as said.

You still missed a dot in the path.pth, and as said, if you wan't to not run my 2 pycairo/pygobject patches, then you might as well remove the os.add_dll_directory call from them, as not usefull then, but semantics.

Let me know if anythings unclear :)

**Comment by mhertz** [comment] 2021-02-25 13:48
Off-topic but i'm closing this with a thank you for the lto enabling commands of libtorrent(and/or boost), nice, thank you! :) I got it from reading your libtorrent ticket and just finished a test-run of it and will merge it to all my deluge2 repo's in a bit - I would have given you credit in the commit-message like with your deluge-console patch I included, and the speed optimization of libtorrent(and/or boost), but have changed to using a script I made to commit which just adds "update" as message, as tired of thinking of descriptive messages and the code IS the changelog as far as i'm concerned, plus one can go into a specific file and check history etc, so was to lazy, also now with 4 deluge2 repo's, so just made script where can run 'gitdelu' command with a flag to dictate if win10 or win7 repos should be updated or in which arch or if all etc so 8 possibilities currently :)

Anyway closing this again, and of-course just reopen if having more questions. I also enabled that discussions feature of all my repo's which is more fitting but your call as said.

I did read the qbittorrent lead-dev once state that a torrent app didn't really need optimized code he thought, as mostly downloading/uploading or copying back and fourth, so possibly it doesn't make very big diff, but either way nice regardless. I believe most of the cpu intensive task in bittorrent is hashing, which I guess then is openssl, so possibly openssl could be manually compilled to enable lto, it's atleast fairly trivial to compile manually I believe, but I will not bother doing that, and only enabled it here because such an easy fix so why not, but cannot help think if it did any reall difference here, then it would be enabled in the various linux packages or windows builds already, which isn't, atleast usually. You can mess with that of-course if interested. I did read another state that in his experience lto could make some small programs slower sometimes, and often it reduces size of apps, but in our case adds 80kb, but read other place that if app coded propperly then no downsides. One stated on libtorrent github that with clang and lto and shared lib, or something, on osx, was slower than without lto, but didn't write back with more info later. Anyway, sorry for long post, again,and just wanted to give credit where due, before commiting :)

Anyway, think i'm gonna lay of the deluge work again for now(in my repos), also now since you're on it again :)

**Closed** 2021-02-25 13:48 UTC
